// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.WebAPI.Data;

namespace SmartSchool.WebAPI.Migrations
{
    [DbContext(typeof(SmartSchoolContext))]
    [Migration("20201120235326_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeAluno")
                        .HasColumnType("TEXT");

                    b.Property<string>("SobrenomeAluno")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneAluno")
                        .HasColumnType("TEXT");

                    b.HasKey("IdAluno");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            IdAluno = 1,
                            NomeAluno = "Marta",
                            SobrenomeAluno = "Kent",
                            TelefoneAluno = "33225555"
                        },
                        new
                        {
                            IdAluno = 2,
                            NomeAluno = "Paula",
                            SobrenomeAluno = "Isabela",
                            TelefoneAluno = "3354288"
                        },
                        new
                        {
                            IdAluno = 3,
                            NomeAluno = "Laura",
                            SobrenomeAluno = "Antonia",
                            TelefoneAluno = "55668899"
                        },
                        new
                        {
                            IdAluno = 4,
                            NomeAluno = "Luiza",
                            SobrenomeAluno = "Maria",
                            TelefoneAluno = "6565659"
                        },
                        new
                        {
                            IdAluno = 5,
                            NomeAluno = "Lucas",
                            SobrenomeAluno = "Machado",
                            TelefoneAluno = "565685415"
                        },
                        new
                        {
                            IdAluno = 6,
                            NomeAluno = "Pedro",
                            SobrenomeAluno = "Alvares",
                            TelefoneAluno = "456454545"
                        },
                        new
                        {
                            IdAluno = 7,
                            NomeAluno = "Paulo",
                            SobrenomeAluno = "José",
                            TelefoneAluno = "9874512"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 3
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 5
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 3
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 1
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 2
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 3
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 4
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.Property<int>("IdDisciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeDisciplina")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDisciplina");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            IdDisciplina = 1,
                            NomeDisciplina = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            IdDisciplina = 2,
                            NomeDisciplina = "Física",
                            ProfessorId = 2
                        },
                        new
                        {
                            IdDisciplina = 3,
                            NomeDisciplina = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            IdDisciplina = 4,
                            NomeDisciplina = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            IdDisciplina = 5,
                            NomeDisciplina = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Professor", b =>
                {
                    b.Property<int>("IdProfessor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeProfessor")
                        .HasColumnType("TEXT");

                    b.HasKey("IdProfessor");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            IdProfessor = 1,
                            NomeProfessor = "Lauro"
                        },
                        new
                        {
                            IdProfessor = 2,
                            NomeProfessor = "Roberto"
                        },
                        new
                        {
                            IdProfessor = 3,
                            NomeProfessor = "Ronaldo"
                        },
                        new
                        {
                            IdProfessor = 4,
                            NomeProfessor = "Rodrigo"
                        },
                        new
                        {
                            IdProfessor = 5,
                            NomeProfessor = "Alexandre"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
